name: MyNotchApp
options:
  bundleIdPrefix: com.prolifiqmezie
  deploymentTarget:
    macOS: "15.0"

targets:
  MyNotchApp:
    type: application
    platform: macOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources/MyNotchApp
        type: group
      - path: MyNotchApp/Assets.xcassets
        type: file
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.prolifiqmezie.MyNotchApp
        SWIFT_VERSION: 6.0
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        INFOPLIST_FILE: MyNotchApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 38G9ST7FYG
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
